In [1]:
import pandas as pd
from fuzzymatch import check_match

In [18]:
cities1 = pd.read_excel("California Cities- 2017 Pop.xlsx")

In [3]:
cities1.set_index('pol1', inplace=True)

In [14]:
cities2 = pd.read_csv('PEP_2017_PEPANNRES_with_ann.csv', encoding='latin1')

In [5]:
df = cities2["GEO.display-label"].str.split(",", n = 1, expand = True)

In [6]:
df.columns=['name', 'state']

In [7]:
df.set_index('name', inplace=True)

In [9]:
left, right = check_match(cities1, df)

In [10]:
len(left)

482

In [11]:
len(right)

483

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 483 entries, Geography to Yucca Valley town
Data columns (total 1 columns):
state    482 non-null object
dtypes: object(1)
memory usage: 7.5+ KB

In [15]:
import fuzzymatcher

In [19]:
cities1

,County,pol1,Population Estimate 2017,pol2,pol3,pol4,pol5,pol6,pol7,pol8,...,ppol33,ppol34,ppol35,ppol35a,ppol41,ppol42,ppol43,ppol44,ppol45,ppol45a
0,Alameda,Alameda,79177,1,1.0,15255,NaN,2,2017-01-18 00:00:00,2017-01-18 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alameda,Albany,20143,1,1.0,2017-9,NaN,2,2017-04-17 00:00:00,2017-04-17 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alameda,Berkeley,122324,1,1.0,NaN,NaN,2,2017-06-25 00:00:00,2017-06-25 00:00:00,...,1986.0,1986.0,1.0,NaN,1.0,1.0,1971.0,1971.0,1.0,NaN
3,Alameda,Dublin,60939,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alameda,Emeryville,11758,1,1.0,17-08,NaN,2,2017-01-17 00:00:00,2017-01-17 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Alameda,Fremont,234962,1,1.0,2017-06,NaN,2,2017-03-07 00:00:00,2017-01-17 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Alameda,Hayward,160500,1,1.0,NaN,NaN,2,2017-06-06 00:00:00,2017-06-06 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alameda,Livermore,90295,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Alameda,Newark,47531,1,1.0,10598,NaN,2,2017-02-23 00:00:00,2017-02-23 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Alameda,Oakland,425195,1,1.0,87036,NaN,2,2018-01-18 00:00:00,2018-01-18 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Alameda,Piedmont,11378,1,1.0,42-18,NaN,2,2018-06-04 00:00:00,2018-06-04 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Alameda,Pleasanton,83007,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Alameda,San Leandro,90553,1,1.0,2017-023,NaN,2,2017-02-21 00:00:00,2017-02-21 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Alameda,Union City,75343,1,1.0,5069-17,NaN,2,2017-05-09 00:00:00,2017-05-09 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Amador,Amador City,190,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Amador,Ione,7827,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Amador,Jackson,4740,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Amador,Plymouth,993,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Amador,Sutter Creek,2575,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Butte,Biggs,1711,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Butte,Chico,93293,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Butte,Gridley,6608,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Butte,Oroville,19121,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Butte,Paradise,26682,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Calaveras,Angels Camp,3807,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Colusa,Colusa,5963,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Colusa,Williams,5349,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Contra Costa,Antioch,111674,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Contra Costa,Brentwood,62433,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Contra Costa,Clayton,12150,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,Sutter,Live Oak,8774,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,Sutter,Yuba City,66860,1,0.0,18-031,NaN,2,2018-05-01 00:00:00,2018-05-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,Tehama,Corning,7592,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,Tehama,Red Bluff,14287,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,Tehama,Tehama,422,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
457,Tulare,Dinuba,24034,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458,Tulare,Exeter,10553,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,Tulare,Farmersville,10778,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
460,Tulare,Lindsay,13303,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,Tulare,Porterville,59145,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462,Tulare,Tulare,63855,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
463,Tulare,Visalia,133010,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
464,Tulare,Woodlake,7649,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
465,Tuolumne,Sonora,4857,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
466,Ventura,Camarillo,67845,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467,Ventura,Fillmore,15812,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,Ventura,Moorpark,36802,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
469,Ventura,Ojai,7582,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470,Ventura,Oxnard,210037,1,1.0,15045,NaN,2,2017-07-25 00:00:00,2017-07-25 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,Ventura,Port Hueneme,22327,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,Ventura,Santa Paula,30313,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
473,Ventura,Simi Valley,126878,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,Ventura,Thousand Oaks,128995,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,Ventura,Ventura,110790,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,Yolo,Davis,68986,1,1.0,14-153,NaN,2,2014-11-05 00:00:00,2014-11-05 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,Yolo,West Sacramento,53512,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,Yolo,Winters,7273,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,Yolo,Woodland,60012,1,1.0,6943,NaN,2,2017-10-03 00:00:00,2017-10-03 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,Yuba,Marysville,12413,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,Yuba,Wheatland,3842,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df = fuzzymatcher.fuzzy_left_join(cities1, cities2, left_on = "pol1", right_on = "GEO.display-label")

In [23]:
df[['pol1', 'GEO.display-label']]

                pol1                            GEO.display-label
0            Alameda                     Alameda city, California
1             Albany                      Albany city, California
2           Berkeley                    Berkeley city, California
3             Dublin                      Dublin city, California
4         Emeryville                  Emeryville city, California
5            Fremont                     Fremont city, California
6            Hayward                     Hayward city, California
7          Livermore                   Livermore city, California
8             Newark                      Newark city, California
9            Oakland                     Oakland city, California
10          Piedmont                    Piedmont city, California
11        Pleasanton                  Pleasanton city, California
12       San Leandro                 San Leandro city, California
13        Union City                  Union City city, California
14       Amador City                 Amador City city, California
15              Ione                        Ione city, California
16           Jackson                     Jackson city, California
17          Plymouth                    Plymouth city, California
18      Sutter Creek                Sutter Creek city, California
19             Biggs                       Biggs city, California
20             Chico                       Chico city, California
21           Gridley                     Gridley city, California
22          Oroville                    Oroville city, California
23          Paradise                    Paradise town, California
24       Angels Camp                      Angels city, California
25            Colusa                      Colusa city, California
26          Williams                    Williams city, California
27           Antioch                     Antioch city, California
28         Brentwood                   Brentwood city, California
29           Clayton                     Clayton city, California
..               ...                                          ...
523         Live Oak                    Live Oak city, California
524        Yuba City                   Yuba City city, California
525          Corning                     Corning city, California
526        Red Bluff                   Red Bluff city, California
527           Tehama                      Tehama city, California
528           Dinuba                      Dinuba city, California
529           Exeter                      Exeter city, California
530     Farmersville                Farmersville city, California
531          Lindsay                     Lindsay city, California
532      Porterville                 Porterville city, California
533           Tulare                      Tulare city, California
534          Visalia                     Visalia city, California
535         Woodlake                    Woodlake city, California
536           Sonora                      Sonora city, California
537        Camarillo                   Camarillo city, California
538         Fillmore                    Fillmore city, California
539         Moorpark                    Moorpark city, California
540             Ojai                        Ojai city, California
541           Oxnard                      Oxnard city, California
542     Port Hueneme                Port Hueneme city, California
543      Santa Paula                 Santa Paula city, California
544      Simi Valley                 Simi Valley city, California
545    Thousand Oaks               Thousand Oaks city, California
546          Ventura  San Buenaventura (Ventura) city, California
547            Davis                       Davis city, California
548  West Sacramento             West Sacramento city, California
549          Winters                     Winters city, California
550         Woodland                    Woodland city, California
551       Marysville                  Marysville city, California
552        Wheatland                   Wheatland city, California

[482 rows x 2 columns]

In [40]:
df[df['GEO.display-label'].duplicated(keep=False)]

,best_match_score,__id_left,__id_right,County,pol1,Population Estimate 2017,pol2,pol3,pol4,pol5,...,rescen42010,resbase42010,respop72010,respop72011,respop72012,respop72013,respop72014,respop72015,respop72016,respop72017
84,-0.024214,83_left,32_right,Kern,California City,13972,1,0.0,2730-04-18 00:00:00,NaN,...,35477,35473,35494,35684,35843,35951,36000,36033,35921,35811
159,0.143525,106_left,32_right,Los Angeles,Bell,35811,0,NaN,NaN,NaN,...,35477,35473,35494,35684,35843,35951,36000,36033,35921,35811

In [29]:
fuzzymatcher.fuzzy_left_join?

Signature:
fuzzymatcher.fuzzy_left_join(
    df_left,
    df_right,
    left_on,
    right_on,
    left_id_col=None,
    right_id_col=None,
)
Docstring: <no docstring>
File:      ~/anaconda3/lib/python3.7/site-packages/fuzzymatcher/__init__.py
Type:      function